// actharness init — scaffold action.test.ts for a given action.yml.

import { resolve, basename, dirname, join } from 'node:path';
import { existsSync, writeFileSync } from 'node:fs';
import { parseAction } from '@actharness/core';
import type { ParsedAction } from '@actharness/types';

export function generateTestScaffold(action: ParsedAction, actionPath: string): string {
  const inputs = action.inputs ?? {};
  const outputs = action.outputs ?? {};
  const actionName = action.name || basename(dirname(actionPath));

  const inputEntries = Object.entries(inputs);
  const outputKeys = Object.keys(outputs);

  const inputsBlock =
    inputEntries.length > 0
      ? `{
      inputs: {
${inputEntries.map(([k, v]) => `        ${k}: ${JSON.stringify(v.default ?? '')},`).join('\n')}
      },
    }`
      : '{}';

  const outputAssertions =
    outputKeys.length > 0
      ? '\n' +
        outputKeys.map((k) => `    expect(result).toHaveOutput(${JSON.stringify(k)});`).join('\n')
      : '';

  return `// Generated by actharness init — no imports needed, globals provided by actharness test.

describe(${JSON.stringify(actionName)}, () => {
  it('succeeds', async () => {
    const result = await actharness('./action.yml').run(${inputsBlock});
    expect(result).toHaveSucceeded();${outputAssertions}
  });
});
`;
}

export function parseInitArgs(args: string[]): string | undefined {
  return args.find((a) => !a.startsWith('--'));
}

export async function initCommand(args: string[]): Promise<number> {
  const rawPath = parseInitArgs(args);
  if (!rawPath) {
    console.error('actharness: init requires an action path (e.g. actharness init ./action.yml)');
    return 1;
  }

  const actionPath = resolve(process.cwd(), rawPath);

  let action: ParsedAction;
  try {
    action = parseAction(actionPath);
  } catch (err) {
    console.error(`actharness: failed to parse ${actionPath}: ${String(err)}`);
    return 1;
  }

  const outPath = join(dirname(actionPath), 'action.test.ts');
  if (existsSync(outPath)) {
    console.error(`actharness: ${outPath} already exists — remove it first to regenerate`);
    return 1;
  }

  const scaffold = generateTestScaffold(action, actionPath);
  writeFileSync(outPath, scaffold, 'utf8');
  console.log(`actharness: wrote ${outPath}`);
  return 0;
}
